# Generated by Django 4.2.7 on 2025-06-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoryes',
            table='category',
        ),
    ]
